import { images, icons } from "../constants";

export const data = [
  {
    id: 1,
    groupName: "Cryptocurrency Moon Boys",
    username: "Sanjay Shendy",
    time: "10h",
    location: "Delhi",
    post: "Your take on the Terra Luna debacle, as 3 Arrows Capital and Celcius Network are in the red 🔴. ",
    profilePicture: images.profilePicture,
    imageUri: images.postImage,
    like: "47.3k",
    dislike: "",
    repost: "47.3k",
    comment: "47.3k",
  },
  {
    id: 2,
    groupName: "Cryptocurrency Moon Boys",
    username: "Sanjay Shendy",
    time: "10h",
    location: "Delhi",
    post: "Your take on the Terra Luna debacle, as 3 Arrows Capital and Celcius Network are in the red 🔴. ",
    profilePicture: images.profilePicture,
    imageUri: images.postImage,
    like: "47.3k",
    dislike: "",
    repost: "47.3k",
    comment: "47.3k",
  },
  {
    id: 3,
    groupName: "Cryptocurrency Moon Boys",
    username: "Sanjay Shendy",
    time: "10h",
    location: "Delhi",
    post: "Your take on the Terra Luna debacle, as 3 Arrows Capital and Celcius Network are in the red 🔴. ",
    profilePicture: images.profilePicture,
    imageUri: images.postImage,
    like: "47.3k",
    dislike: "",
    repost: "47.3k",
    comment: "47.3k",
  },
  {
    id: 4,
    groupName: "Cryptocurrency Moon Boys",
    username: "Sanjay Shendy",
    time: "10h",
    location: "Delhi",
    post: "Your take on the Terra Luna debacle, as 3 Arrows Capital and Celcius Network are in the red 🔴. ",
    profilePicture: images.profilePicture,
    imageUri: images.postImage,
    like: "47.3k",
    dislike: "",
    repost: "47.3k",
    comment: "47.3k",
  },
];

export const memberShipData = [
  {
    id: 1,
    primaryAccountImage: images.primaryAccount,
    groupImage: images.groupImage,
    memberOf: "Apple Fans",
    totalMembers: "7.0m members",
  },
  {
    id: 2,
    primaryAccountImage: images.primaryAccount,
    groupImage: images.groupImage,
    memberOf: "Apple Fans",
    totalMembers: "7.0m members",
  },
  {
    id: 3,
    primaryAccountImage: images.primaryAccount,
    groupImage: images.groupImage,
    memberOf: "Apple Fans",
    totalMembers: "7.0m members",
  },
  {
    id: 4,
    primaryAccountImage: images.primaryAccount,
    groupImage: images.groupImage,
    memberOf: "Apple Fans",
    totalMembers: "7.0m members",
  },
  {
    id: 5,
    primaryAccountImage: images.primaryAccount,
    groupImage: images.groupImage,
    memberOf: "Apple Fans",
    totalMembers: "7.0m members",
  },
  {
    id: 6,
    primaryAccountImage: images.primaryAccount,
    groupImage: images.groupImage,
    memberOf: "Apple Fans",
    totalMembers: "7.0m members",
  },
];

export const commentData = [
  {
    id: 1,
    headerText: "The playground of the lunatics...  ",
    text: "Lunatics 2.0",
    time: "20 h",
    vote: "75votes",
    subText:
      "The reasons for luna debacle unfolding today with respect to 3 Arrows Capital",
  },
  {
    id: 2,
    headerText: "The playground of the lunatics...  ",
    text: "Lunatics 2.0",
    time: "20 h",
    vote: "75votes",
    subText:
      "The reasons for luna debacle unfolding today with respect to 3 Arrows Capital",
  },
  {
    id: 3,
    headerText: "The playground of the lunatics...  ",
    text: "Lunatics 2.0",
    time: "20 h",
    vote: "75votes",
    subText:
      "The reasons for luna debacle unfolding today with respect to 3 Arrows Capital",
  },
  {
    id: 4,
    headerText: "The playground of the lunatics...  ",
    text: "Lunatics 2.0",
    time: "20 h",
    vote: "75votes",
    subText:
      "The reasons for luna debacle unfolding today with respect to 3 Arrows Capital",
  },
  {
    id: 5,
    headerText: "The playground of the lunatics...  ",
    text: "Lunatics 2.0",
    time: "20 h",
    vote: "75votes",
    subText:
      "The reasons for luna debacle unfolding today with respect to 3 Arrows Capital",
  },
  {
    id: 6,
    headerText: "The playground of the lunatics...  ",
    text: "Lunatics 2.0",
    time: "20 h",
    vote: "75votes",
    subText:
      "The reasons for luna debacle unfolding today with respect to 3 Arrows Capital",
  },
  {
    id: 7,
    headerText: "The playground of the lunatics...  ",
    text: "Lunatics 2.0",
    time: "20 h",
    vote: "75votes",
    subText:
      "The reasons for luna debacle unfolding today with respect to 3 Arrows Capital",
  },
];

export const portFolio = [
  {
    id: 1,
    iconUrl: icons.btc,
    name: "Bitcoin",
    acy: "BTC",
    price: "$36,701.78",
    inflation: "-6.28%",
  },
  {
    id: 2,
    iconUrl: icons.bch,
    name: "Bitcoin Cash",
    acy: "BCH",
    price: "$665.25",
    inflation: "-9.2%",
  },
  {
    id: 3,
    iconUrl: icons.eth,
    name: "Ethereum",
    acy: "ETH",
    price: "$2,629.70",
    inflation: "-8.12%",
  },
  {
    id: 4,
    iconUrl: icons.etc,
    name: "Lite Coin",
    acy: "LTC",
    price: "$175.76",
    inflation: "-10.01%",
  },
  {
    id: 5,
    iconUrl: icons.ltc,
    name: "Lite Coin",
    acy: "LTC",
    price: "$175.76",
    inflation: "-10.01%",
  },

  {
    id: 6,
    iconUrl: icons.ox,
    name: "Ox",
    acy: "ZRX",
    price: "$1.07",
    inflation: "-10.01%",
  },
  {
    id: 7,
    iconUrl: icons.xrp,
    name: "XRP",
    acy: "XRP",
    price: "$175.76",
    inflation: "-10.01%",
  },
];
